# REPRESENTATION
POLYGLOT_UNK = str("<UNK>")
PADDING_CHAR = "<*>"

# MODEL PARAMS
DEFAULT_CHAR_DIM = 20
DEFAULT_HIDDEN_DIM = 50
DEFAULT_WORD_DIM = 64
EARLY_STOPPING_CONST = 5

# LSTM
DEFAULT_LSTM_LAYERS = 1

# CNN
DEFAULT_WINDOW_WIDTH = 3
DEFAULT_POOLING_MAXK = 1
DEFAULT_STRIDE = 1
DEFAULT_CNN_LAYERS = 1
